---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      box: chef/ubuntu-14.04
    attribute:
      apt:
        compile_time_update: yes
  - name: centos-6.6
    driver:
      box: chef/centos-6.6

suites:
  - name: default
    run_list:
      - recipe[yumrepo_server::default]
    attributes:
  - name: custom_port
    run_list:
      - recipe[yumrepo_server::default]
    attributes:
      yum:
        server:
          http_port: 9090
